import LeftMainSidebarData from "./LeftMainSidebarData";

function LeftMainSidebar({}) {
  const dataServices = [
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
    {
      data: "UTC09",
      figure1: "1458.75",
      figure2: "800.83",
      figure3: "89.97",
      MainText: "p_main_txt_white",
      FigOne: "p_txt_left_green",
      FigTwo: "p_txt_left_green",
      FigThree: "p_txt_left_green",
    },
  ];
  return (
    <div class="col-md-3">
      <div class="main_sidebar_left">
        <div class="nav_icon">NFT</div>
        {dataServices.map((x) => (
          <LeftMainSidebarData
            data={x.data}
            figure1={x.figure1}
            figure2={x.figure2}
            figure3={x.figure3}
            MainText={x.MainText}
            FigOne={x.FigOne}
            FigTwo={x.FigTwo}
            FigThree={x.FigThree}
          />
        ))}
      </div>
    </div>
  );
}
export default LeftMainSidebar;
